### ISSUE TITLE
Allow port number for app to be specified via the UI

### ISSUE THREAD

**Issue by miltontony** [universalcore/unicore-mc#15]
The default is to use sockets. If a port number is required, it should be optional in the UI

**Comment by smn** [comment]
I don't see any benefit to allowing port numbers at this point. Perhaps when things run in docker containers but not now...

**Comment by miltontony** [comment]
@smn It's more of an option to choose between using sockets vs ports via the UI. But not for now - possible for when Mission Control is a stable product

**Comment by smn** [comment]
MC is now stable enough for us to be relying on it in production, I still don't see a case for going back to using port numbers?

**Comment by miltontony** [comment]
:+1:
